countries.json
Not much to it. Just a 'n' too many.
=> fix spelling in german translation for Egypt in countries.json

README.md
Now that the relevance field has been removed I think that references to in in the README should also be removed.
=> Remove documentation referring to removed relevance field.

README.md
The documentation had been updated to remove reference to relevance except for the source list. This PR removes the link to the relevance source.
=> Removed Relevance from sources list.

countries.json
Sardinian is a recognized minority language in Italy.
=> added Sardinian

countries.json
- updated official names based on Encyclopédie Larousse online and data
from the French Foreign Office (wikipedia clearly not a reliable source
of infos!)
- reverted back "Confédération helvétique" to "Confédération suisse" as
it was the right name
- Made some changes on common names when appropriate, based on the same
sources as mentioned above
- cleared unwanted spaces after "d' " or after "( "
- corrected some "de" that needed to be "du"
=> Updates to translations:fra (see details)

src/MLD/Converter/AbstractJsonConverter.php
If the `languages` key was excluded it would still appear in the JSON output files.
=> Fixes #162

src/MLD/Console/Command/ExportCommand.php
This change allow overriding the default command name "convert" to use whatever is passed in the third parameter to the constructor.  This was previously ignored due to the forced setName() in configure().
=> Allow setting a custom command name

countries.json
Small addition of one line.
Added the Dutch translation for Kosovo, this was the only country without a Dutch translation.
=> Add nld translation for Kosovo

countries.json
**Czechia** [was approved](http://www.mzv.cz/jnp/cz/udalosti_a_media/tiskove_zpravy/x_2016_05_02_vlada_schvalila_czechia.html) as the official English short name. For other languages were also _created_ short names (e.g., French, Arabian, Chinese).
It has been already published in the [United Nations](http://unterm.un.org/UNTERM/Display/Record/UNHQ/NA/4275087d-4018-4082-899d-95f37efeda65) name databases and in the official [ISO 3166](https://www.iso.org/obp/ui/#iso:code:3166:CZ) country codes list. It's recommended (by the government) to use short name.
I know that Czechia is not commonly used, however Czech Republic had no official short name before.
=> Czech Republic short names

countries.json
I have corrected a few common names.
I think the official names must not have been present when the initial Welsh translations were added as they were all English, I have added the Welsh for official names where English was used but called Welsh.
I haven't changed the 186 countries with no Welsh translations, that is another pull request for another day.
I noticed ŵ is represented by '\u0175' but wasn't sure whether î (Belize - Belîs) should the represented similarly or not, let me know if you want me to change that.
=> Welsh additions and corrections

index.md
Adds required space between the `###...` and the header text in the gh-pages md file.
(Header with missing space is displayed as a literal `###Header Text`.)
=> Fix missing spaces in markdown headers

countries.json
This is to fix https://github.com/mledoze/countries/issues/4
and use Traditional Chinese instead of Simplified Chinese for Taiwan, because `Simplified Chinese` is for China, and Taiwan is using `Traditional Chinese`. 
Thanks :)
=> remove `province of China` and use Traditional Chinese for Taiwan

countries.json
centered on Wake Island, UM's largest territory.
sources: 
- [List of territories in UM](https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands#Islands)
- [Coordinates of Wake Island](https://tools.wmflabs.org/geohack/geohack.php?pagename=United_States_Minor_Outlying_Islands&params=19_18_N_166_38_E_type:isle_region:US-UM&title=Wake+Island)
=> Add lat/lng data for United States Minor Outlying Islands/UM

.travis.yml, composer.json, composer.lock
add dependency "roave/security-advisories"
update dependencies:
- php (>=5.5.9 => >=5.6.33)
- symfony/console (v3.3.6 => v4.0.4)
- symfony/yaml (v3.3.6 => v4.0.4)
changed PHP version to 7.2 for Travis CI builds
=> Update dependencies and PHP version for Travis CI

composer.json
As doc says, ```roave/security-advisories``` should be on ```require-dev``` section.
https://github.com/Roave/SecurityAdvisories#usage
It will free this library from that dependency.
=> Moved roave/security-advisories to require-dev

src/MLD/Console/Command/ExportCommand.php
Currently the convert script always displays the total number of formats
it is able to export to, no matter how many of which have actually been
selected:
```
Converted data for 250 countries into 5 formats.
```
This is now fixed. Calling the convert script with, say, `-f csv` it now
displays `[...] into 1 format.`
=> Fix cli info format

countries.json
- Official name of NL is "Kingdom of the Netherlands" instead of "Netherlands";
- Native name of NL is "Koninkrijk der Nederlanden" instead of "Nederland".
Source: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/26th-gegn-docs/WP/WP54_UNGEGN%20WG%20Country%20Names%20Document%202011.pdf
=> Update official and native name of the Netherlands

countries.json
currently the Macau demonym is Chinese, I think should be set to Macanese, as described in Wikipedia: 
[Macau](https://en.wikipedia.org/wiki/Macau)
=> Fix Macau demonym

countries.json
currently the Vatican City demonym is Italian, I think should be set to Vatican, as described in Wikipedia: [List_of_adjectival_and_demonymic_forms_for_countries_and_nations](https://en.wikipedia.org/wiki/List_of_adjectival_and_demonymic_forms_for_countries_and_nations)
=> Fix Vatican City demonym

countries.json
Hey! I did the translations to Polish for every country. Accented characters are all encoded. My source for the translations: http://pl.wikipedia.org/wiki/ISO_3166-1
=> Polish translations

countries.json
the German (shorter) common name is "Südafrika" instead of "Republik Südafrika"
see https://de.wikipedia.org/wiki/S%C3%BCdafrika
=> Republik Südafrika -> Südafrika

countries.json
As mentioned by @ndawg in #289, Swaziland is now officially called Eswatini (see https://www.iso.org/obp/ui#iso:code:3166:SZ).
Note: I didn't change the official name for every translation and I also left the common name unchanged for now for almost all languages.
=> Rename Swaziland to Eswatini

countries.json
I found out the official and common name of South Korea in Korean language was reversed. I made a correction on that.
Also, I've update Japanese translation of 'Korea' they commly call us '韓国' (Kankoku)
=> Correction on official and common country name of Korea

countries.json
The "translations" objects for "Hong Kong" and "Kiribati" are apparently corrupt. 
Please see the diff.
=> Fix invalid "translations" objects.

countries.json
The official German name for Nepal (Demokratische Bundesrepublik Nepal) contained a superfluous letter.
=> Official German name for Nepal

README.md, countries.json
- change format of `currencies` property: use currency code as keys
- move `currencies` property back to its previous position
- reorder currencies codes alphabetically
=> Currencies refactoring

LICENSE
Hi,
The full text of the license needs to be stated clearly to avoid ambiguity. Without this disambiguation, ODbL is not recognized and applied correctly. This will also allow make it fully parsable, for machine-readable purposes.
Thanks for this project and your great work!
=> Add the full ODbL license

countries.json
Re: issue #351 
Change "United State Dollar" to "United States Dollar"
=> Change 'United State Dollar' to 'United States Dollar'

README.md, countries.json
Hi,
First of all, thank you for this project 💯 
As suggested in #165, I added translated demonyms (in French). 
It is indexed by `f` or `m` to manage gender inflection. 
I decided to **add** a new key rather than changing the structure, to keep things backward compatible. Tell me if it's ok for you. 
I used a PHP script to decode/encode the `countries.json` file, so some indentation may have changed (I used `json_encode` with `JSON_PRETTY_PRINT` option). You can add `?w=1` to the GitHub URL to get rid of whitespace changes.
=> Add translated demonyms in French.

README.md, countries.json
=> Merge demonym into demonyms

countries.json
Should be `Haití` in Spanish translation
=> Fix Spanish spelling for Haiti

countries.json
Added "Macedonia, The Former Yugoslav Republic of"
I did not commit the generated dist folder as i noticed it modified more than then just Macedonia and I did not want to override others contributions
=> Added altSpelling to Macedonia

CHANGELOG.md, countries.json
This pull request adds the Swedish translations to `countries.json`, both official ones as well as common ones. 
The common names have been sourced from the [ISO 3166](https://sv.wikipedia.org/wiki/ISO_3166#ISO_3166-1-koder) article on Swedish Wikipedia.
The official names have been sourced from the Swedish Wikipedia pages of individual countries. Hence, for example `Finland` becomes `Republiken Finland`, as it is defined in [Finland's Wikipedia article](https://sv.wikipedia.org/wiki/Finland). In these articles, the preceding text "officiellt" (officially) or "formellt" (formally) signifies the official naming.
When no official naming has been provided in the Wikipedia article, I have kept both the common and official name the same.
If I'm missing something or something is wrong, do say! …
=> Add Swedish translations to countries.json (both common and official)

index.d.ts
This updates the TypeScript types to reflect the new data structure from countries.json.
This was mentioned here: #415
(And sorry, I renamed the branch which closed the previous PR – that was not intended.)
=> Update demonyms TS type (fixes #415)

countries.json
Empty currencies has type array ( [] ), it's wrong, they should have object type
Now it's generates errors when try to unmarshal it to objects
=> Changed array to object for empty currencies

countries.json
Hi I noticed that Guinea-Bissau has unMember: false, but it is actually a member. (Data source here: https://www.un.org/en/about-us/member-states#gotoG). Here's a pull request to rectify that.
Thanks
=> #470 Guinea-Bissau should be a UN member

countries.json
As of 1 Jan 2023, the Euro is the official currency. HRK will be accepted until 14 Jan 2023
=> Updated Croatia's currency to EUR as the HRK

countries.json
Hi I noticed that Guinea-Bissau has `unMember: false`, but it is actually a member. (Data source here: https://www.un.org/en/about-us/member-states#gotoG). Here's a pull request to rectify that.
Thanks,
Ed
=> Update Guinea-Bissau UN membership to true

countries.json
Change to official name "Republic of Türkiye"
https://www.mfa.gov.tr/constitution-of-the-republic-of-turkey.en.mfa
https://en.wikipedia.org/wiki/Turkey
https://balkaninsight.com/2022/06/02/un-confirms-turkeys-official-name-change-to-turkiye/
=> Update countries.json (Turkey)

index.d.ts
Change the type of the `demonyms` property from optional to required. Now, it must have a defined value for each languageCode.
Before: `demonyms: { [languageCode: string]?: Demonyms }`
After:  `demonyms: { [languageCode: string]: Demonyms }`
=> Change demonyms property type

countries.json
>[!NOTE]
> All the common and official names of the countries were taken from the respective Wikipedia pages in Arabic.
This PR is a follow-up on #256
This PR adds Arabic translation to all the countries in `countries.json`
It also updates some of the native names in Arabic, as well as remove unnecessary characters, namely `\u200e` and `\u200f`
=> feat: Add Arabic translation to all countries

countries.json
I'm using altSpellings in countries.json to map country names to country codes for parsing Covid-19 data from ourworldindata.org. The well-known website uses a few names that aren't yet found as altSpellings.
=> Add alt spellings found in ourworldindata.org Covid-19 data

countries.json
Change English common name of "Republic of the Congo" to "Congo" (iso CG) not to confuse with "the Democratic Republic of the Congo" (iso = CD)
=> CG common name = "Congo" fix #564

countries.json
Change the many occurrences of Swatziland (SZ) to the language version of Eswatini based on Wikidata page https://www.wikidata.org/wiki/Q1050 and each Wikipedia page
=> Change Swatziland (SZ) to the Eswatini fix #566

CHANGELOG.md, countries.json
Use the letter 'đ' instead of the two-letter combination 'dj'.
Same meaning, more correctly like this.
Sources:
- [The Ministry of Foreign Affairs of the Republic of Serbia: Bilateral Cooperation - Mađarska](https://www.mfa.gov.rs/lat/spoljna-politika/bilateralna-saradnja/madjarska)
=> Fix Serbian 'common' and 'official' name for Hungarian
