countries.json
Add mapping for ISO 3166 names.
=> Add ISO 3166-2 names

countries.json
Added Tamil to the list of Indian languages
=> Added Tamil to the list of Indian languages

countries.json
=> Add Basque language name

countries.json
Fix for https://github.com/mledoze/countries/issues/143
=> Fix Solomon Islands Dollar ISO-Code

countries.json
Fixed some typos, uppercased all officials, changed officicals according
to Wikipedia.
=> German language fix

countries.json
Various updates, changes and corrections. Also did some harmonization on the dashes.
=> Various updates, changes and corrections

countries.json
I added French translations for Kosovo and Curaçao.
=> Added missing French translations

countries.json
https://de.wikipedia.org/wiki/Cura%C3%A7ao
https://de.wikipedia.org/wiki/Kosovo
https://www.destatis.de/DE/Methoden/Klassifikationen/Aussenhandel/Laenderverzeichnis.pdf?__blob=publicationFile
=> Add german translations for Kosovo and Curacao

countries.json
- Fix #175 
- Full Chinese translation.
Cannot compile because of #176
=> Fix Chinese language code. Add Chinese translation.

README.md
=> Updated @herrniemand's nickname.

countries.json
honduras, samoa, macau
hope now it is finished :)
=> missing translations

countries.json
Afteer seeing this online, I have noticed some grammar issues, so I corrected them. Now it finaly should be ok. :)
=> corrections in grammar

countries.json
I've changed the subregion of Mexico
=> Mexico is located in North America

README.md
Clean README.md format (titles)
=> Update README.md format

countries.json
=> remove South Sudan from Chad's neighbors

README.md, composer.json, countries.php, src/MLD/Console/Command/ExportCommand.php
=> New options to convert command

countries.json
Also fixes https://github.com/mledoze/countries/issues/236
=> Fixed non-existing 'svk' language

countries.json
From https://github.com/fayder/restcountries/pull/75
=> add CKD as currency of Cook Islands

countries.json
=> Added "Antarctic" region

README.md, countries.json
Replaces PR #190 by @8alery.
Additional fixes:
- Belize: renamed "country" property to "flag"
- added flag for Aruba
Verification (248 records):
🇦🇼 Aruba
🇦🇫 Afghanistan
🇦🇴 Angola
🇦🇮 Anguilla
🇦🇽 Åland Islands
🇦🇱 Albania
🇦🇩 Andorra
🇦🇪 United Arab Emirates
🇦🇷 Argentina
🇦🇲 Armenia
🇦🇸 American Samoa
🇦🇶 Antarctica
🇹🇫 French Southern and Antarctic Lands
🇦🇬 Antigua and Barbuda
🇦🇺 Australia
🇦🇹 Austria
🇦🇿 Azerbaijan
🇧🇮 Burundi
🇧🇪 Belgium
🇧🇯 Benin
🇧🇫 Burkina Faso
🇧🇩 Bangladesh
🇧🇬 Bulgaria
🇧🇭 Bahrain
🇧🇸 Bahamas
🇧🇦 Bosnia and Herzegovina
🇧🇱 Saint Barthélemy
🇧🇾 Belarus
🇧🇿 Belize
🇧🇲 Bermuda
🇧🇴 Bolivia
🇧🇷 Brazil
🇧🇧 Barbados
🇧🇳 Brunei
🇧🇹 Bhutan
🇧🇻 Bouvet Island
🇧🇼 Botswana
🇨🇫 Central African Republic
🇨🇦 Canada
🇨🇨 Cocos (Keeling) Islands
🇨🇭 Switzerland
🇨🇱 Chile
🇨🇳 China
🇨🇮 Ivory Coast
🇨🇲 Cameroon
🇨🇩 DR …
=> Added emoji flags

countries.php, src/MLD/Converter/AbstractConverter.php, src/MLD/Converter/AbstractJsonConverter.php, src/MLD/Converter/CsvConverter.php, src/MLD/Converter/JsonConverter.php, src/MLD/Converter/JsonConverterUnicode.php, src/MLD/Converter/XmlConverter.php, src/MLD/Converter/YamlConverter.php
This pull request removes the Hungarian notation style that was used originally in the PHP code.
=> Remove hungarian notation

src/MLD/Console/Command/ExportCommand.php, src/MLD/Converter/AbstractConverter.php, src/MLD/Converter/AbstractJsonConverter.php, src/MLD/Converter/ConverterInterface.php, src/MLD/Converter/CsvConverter.php, src/MLD/Converter/JsonConverter.php, src/MLD/Converter/JsonConverterUnicode.php, src/MLD/Converter/XmlConverter.php, src/MLD/Converter/YamlConverter.php
This pull requests format the build code to comply with the PSR2 specification.
=> Format code to comply with PSR2

countries.json
Hi. I added a Czech translation (with language code "ces") for all countries. All accented characters are escaped.
=> Czech Translation

countries.json
I tried to update some common and official names of the countries for the german translation according to my understanding and with the help of some german sources:
* Official list of country names in German (http://www.stagn.de/SharedDocs/Downloads/DE/StAGN_Publikationen/140408_STAATENNAMEN_13_ol.pdf?__blob=publicationFile&v=4)
* German Federal Foreign Office (https://www.auswaertiges-amt.de/de/aussenpolitik/laender)
* German Wikipedia (https://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste)
=> Updated some German translations

README.md
To prevent further pointless discussions as are happening in https://github.com/mledoze/countries/issues/285.
=> Clarify data source authority in top of README

countries.json
=> Add missing currency codes

countries.json
=> Saint Kitts and Nevis name fixes

composer.json, composer.lock, src/MLD/Console/Command/ExportCommand.php
Add Symfony 5 support 
#SymfonyHackday
=> Add Symfony 5 support

countries.json
=> Fix wrong Iran language code, updated the label

CHANGELOG.md
Add a changelog following the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.
The [first release v1.0](https://github.com/mledoze/countries/releases/tag/v1.0) goes back to July 2013.
Thank you to all of you who have [contributed](https://github.com/mledoze/countries/graphs/contributors) to this project!
=> add a CHANGELOG.md

CHANGELOG.md, package.json
=> add `files` in `package.json` to reduce package size

CHANGELOG.md, data/cub.svg
=> remove duplicate viewBow for Cuba's flag

README.md
Add field `callingCodes`, `unMember`, remove field `demonym` and
update field for currencies in the sample in README.md file to
reflect the breaking changes introduced in v3.0.0 and v4.0.0:
- v3.0.0: `currency` is renamed to `currencies` and the format
changed from array to an object with currency code as keys.
- v4.0.0: `demonym` is merged to `demonyms` and removed.
=> Update the sample in the README file

CHANGELOG.md, countries.json
=> fix Montenegrin language code

CHANGELOG.md, composer.json, package.json
fix #478 
@Gerschtli that should do it
=> fix files listed in npm package

README.md
=> fix convert -i option in README.md

CHANGELOG.md, index.mjs
@fahad39 will it fix the error of #502?
=> fix error when running index.mjs

countries.json
#529 may be closed with this PR
=> Kazakhstan capital renamed from Nur-Sultan to Astana

countries.json
=> Fix common German name for Belarus

countries.json
Hi! Added all common and official country names for breton language.
Also regenerated the dist folder.
=> Add breton (bre) translations
